### PR TITLE
Replace Googler aliases with their GitHub users.

### PR DESCRIPTION
**Pull request by philwo**
FYI @meisterT @laszlocsomor @buchgr

### CODE REVIEW

**Comment by philwo** [comment]
lindleyf is not in our username <=> GitHub map, so I left the name as is.

**Comment by laszlocsomor** [comment]
Thanks! WDYT about changing the user names to links to the github profiles?

**Comment by philwo** [comment]
Arghh. I thought GitHub would do that automatically for "@" prefixed usernames...

Yeah, would definitely look nicer. I'll have a look.

**Comment by philwo** [comment]
@laszlocsomor Done!

**Comment by laurentlb** [comment]
lgtm

**Comment by jin** [comment]
Much better idea :-)

**Pull request merged**
