### PR TITLE
Add proposal for support C++20 Modules

### PR DESCRIPTION
**Pull request by PikachuHyA**

### CODE REVIEW

**Comment by lberki** [comment]
Mind linking this into `README.md` under the "under review" section?

**Comment by lberki** [comment]
Thanks! It appears that you also need to sign our CLA (I missed this yesterday, sorry about that)

My understanding is that you work for Alibaba and my data shows that Alibaba Group already has a corporate CLA signed, which means that you _should_ be covered, but our bot seems to disagree. Instructions are [here](https://github.com/bazelbuild/proposals/pull/354/checks?check_run_id=18066413418) to fix it ; you probably either need to add the e-mail address to the set of people covered by your CLA or use a different e-mail on your git commit. 

Sorry about the red tape.

**Comment by PikachuHyA** [comment]
> It appears that you also need to sign our CLA
done

**Comment by lberki** [comment]
Thanks! I'll merge this now.

**Review by lberki — APPROVED** [review]

**Pull request merged**
