### PR TITLE
Exec platform scoped spawn strategies

### PR DESCRIPTION
**Pull request by Silic0nS0ldier**
Proposal to make spawn strategies aware of execution platforms via the existing strategy CLI flags.

## Goals

* Keep the scope small, such that this proposal is easier to review and implement.
* No new concepts, build off what already exists.
* Make it easy for existing workflows to take advantage (e.g. `--config remote` to enable remote execution in a build).

## Prior Proposals

Solutions to this problem space have been proposed twice before (that I know of).

- 2019-08-01 - [2019-06-25-platforms-strategies.md](https://github.com/bazelbuild/proposals/blob/1032d7d8fbe0e518e88482e7c532eb409ef6f1ac/designs/2019-06-25-platforms-strategies.md) by @katre
- 2023-03-31 - [Execution Platforms vs. Strategies](https://docs.google.com/document/d/1U9HzdDmtRnm244CaRM6JV-q2408mbNODAMewcGjnnbM) by @katre and @aragos

## Potential Follow-ups

- `--remote_local_fallback` is unresolved by this proposal as it does not rerun spawn strategy selection, however all the pieces required to support such behaviour are in place. 
  Supporting this will require changing behaviour (new flag or major release required) and goes beyond the scope of this proposal (mnemonics, description matching regex, and so on would be considered in addition to execution platform scoping).
  It would make sense to see this addressed in a separate proposal.

### CODE REVIEW

**Review by katre — DISMISSED** [review]
Thanks for submitting this! The proposal looks well-formed. I have several review comments, but I'll hold them until this is actually in the review phase.

Go ahead and add me as reviewer (and update the bit about `--platforms` for clarity). Also please note @lberki's comment about the README.

**Comment by katre** [comment]
@tjgq Feel free to bring that up in the review discussion: this PR should be focused on getting the proposal to a state where it's ready for discussion and review.

**Comment by Silic0nS0ldier** [comment]
@lberki this is good to go.

**Comment by lberki** [comment]
aye aye sir

**Review by lberki — APPROVED** [review]

**Comment by lberki** [comment]
I'll go ahead and dismiss @katre 's review since the latest version seem to address both points (adding a reviewer and README.md)

**Comment by Silic0nS0ldier** [comment]
Discussion started at https://github.com/bazelbuild/bazel/discussions/20497

**Pull request merged**
