### PR TITLE
More cleanup of document states.

### PR DESCRIPTION
**Pull request by lberki**
I aggressively moved proposals to Dropped/Implemented so that the slate
is as clean as possible.

### CODE REVIEW

**Comment by lberki** [comment]
My understanding of the state of affairs is as follows:

* "Starlark Directory Expansion in Args MapEach" is implemented and `map_each` can take a `directory_expander` argument
* We still want to rename Skydoc to Stardoc, but no one is actively working on it
* "Experimental Content-Based Output Paths" hasn't seen  a lot of action recently
*  "Dependency Discovery Proposal" is stalled
* We don't have plans to implement "Remote Repository Cache"
* "Test execution on Windows without Bash" -- it look like this is wasn't eventually implemented because I don't see references to `test_wrapper.exe`, but maybe it was?
* "Moving Skylark out of Bazel" happened inasmuch as the dependency structure is clean, but we have no plans of moving the code out to a separate Git repository
* "Remote Downloads" is implemented as the `--experimental_remote_downloader` flag
* I haven't been able to find any information about "Propagate tags from the targets to actions", so I assume it's dead
* I haven't been able to find any information about "Propagate tags from the targets to actions", so I assume it's dead

I'll add reviewers to this pull request who I think will be able to tell whether the above statements are correct.

**Comment by lberki** [comment]
@aiuto is my understanding correct that you are still planning to implement "Rules for software license compliance?"

**Review by philwo — APPROVED** [review]

**Comment by lberki** [comment]
@philwo is it the case that "Dependency Discovery Proposal" and "Remote Repository Cache" are stalled?

**Comment by lberki** [comment]
@brandjon am I correct in the following?

* "Starlark Directory Expansion in Args MapEach" is implemented
* We are not planning anymore to move Starlark to a separate git repository
* "Semantics of the expansion of Labels" is dead

**Comment by lberki** [comment]
@meteorcloudy what is the state of "Test execution on Windows without bash?"

**Comment by meteorcloudy** [comment]
> @meteorcloudy what is the state of "Test execution on Windows without bash?"

It has already been implemented, we no longer require Bash for running tests on Windows.

**Review by meteorcloudy — APPROVED** [review]
Approving for Windows related change.

**Comment by meteorcloudy** [comment]
Wait.. I thought it's in the implemented section, can you move it there?

**Comment by meteorcloudy** [comment]
> it look like this is wasn't eventually implemented because I don't see references to test_wrapper.exe, but maybe it was?

The test_wrapper.exe was renamed to just tw.exe to save some characters for the file path because it's precious on Windows. 
Check https://github.com/bazelbuild/bazel/tree/master/tools/test/windows

**Comment by lberki** [comment]
Thanks! Moved "Test execution on Windows without Bash" to the "Implemented" section.

**Review by aiuto — APPROVED** [review]

**Comment by brandjon** [comment]
> We still want to rename Skydoc to Stardoc, but no one is actively working on it

We have renamed it, in the sense that bazelbuild/skydoc contains unmaintained code and bazelbuild/stardoc is canonical. However, there may be more steps recommended by that doc that have not been implemented. Certainly the subdomain skydoc.bazel.build was never renamed.

> "Moving Skylark out of Bazel" happened inasmuch as the dependency structure is clean, but we have no plans of moving the code out to a separate Git repository

Correct. We dropped the launch of a separate repo to hold the Java code. That's blocked on cleaning up the interpreter's Java API to the point that we can promise to essentially never change it, and getting there is work we're not committing to at the moment.

Without verifying the diff, LGTM on the basis of that summary w.r.t. those two docs.

**Review by brandjon — APPROVED** [review]

**Pull request merged**
