### PR TITLE
Add Bazel Ruleset GOVERNANCE | MECHANICS

### PR DESCRIPTION
**Pull request by comius**

### CODE REVIEW

**Comment by lberki** [comment]
Mind a adding a "Status" field to the document? It looks like from the comment threads that there are disagreements about the desired governance structure, so I think it's too early to codify this as gospel.

**Comment by alexeagle** [comment]
@comius is this on your agenda for our Authoring Rulesets bof?

**Comment by comius** [comment]
> Mind adding a "Status" field to the document? It looks like from the comment threads that there are disagreements about the desired governance structure, so I think it's too early to codify this as gospel.

Done

**Comment by lberki** [comment]
Far be it from me to nitpick, but is the ALL CAPS NECESSARY?

**Review by lberki — APPROVED** [review]

**Comment by comius** [comment]
> @comius is this on your agenda for our Authoring Rulesets bof?

Sure. Let's see first if I can address the comments, so that I get more familiar with the domain. (I'm not the author).

@alexeagle do you think you'd be a good primary reviewer? Or could you suggest somebody else?

**Comment by alexeagle** [comment]
Sure, I already did a preliminary review as Radhika was composing this, I'm happy to be a reviewer of record, thanks.

**Review by lberki — APPROVED** [review]

**Pull request merged**
