### PR TITLE
Adding a proposal for Target-level execution properties

### PR DESCRIPTION
**Pull request by agoulti**
A proposal for allowing execution properties to be set on a target directly, allowing the user to decouple it from platform resolution

### CODE REVIEW

**Comment by jin** [comment]
Is this under review or implemented?

**Comment by agoulti** [comment]
It's approved but not yet implemented.

**Comment by agoulti** [comment]
Thanks for pointing this out, I added it to the wrong column originally

**Comment by aiuto** [comment]
This is lingering. Can you merge and repush. I can not figure out the github UI for me to fix the merge conflict.

**Comment by aiuto** [comment]
Never mind. I figured ou the merge.

**Pull request merged**
