### PR TITLE
Draft: Remote Repository Cache

### PR DESCRIPTION
**Pull request by jmillikin-stripe**

### CODE REVIEW

**Comment by jin** [comment]
@jmillikin-stripe, has a lead reviewer been assigned for you?

**Comment by jmillikin-stripe** [comment]
No, I haven't got a reviewer yet, and I'd greatly appreciate being assigned one.

**Comment by jin** [comment]
@dslomov this looks related to external repos, can you take this?

**Comment by laurentlb** [comment]
@buchgr, @aehlig 
Can you deal with the PR? (https://bazel.build/designs/#create-a-pull-request)

**Comment by dslomov** [comment]
Merging this: I have added @aehlig and @buchgr as reviewers

**Pull request merged**
