### PR TITLE
Update toolchain transitions design

### PR DESCRIPTION
**Pull request by katre**
Reflects the latest comments from the design review thread.

Please comment only on formatting and style: actual design discussion should still take place at [the review thread](https://groups.google.com/forum/!msg/bazel-dev/5osWxhoF0Fk/1yw4MXrEBQAJ).

### CODE REVIEW

**Comment by brandjon** [comment]
> As an example, the `genrule` rule has an attribute named `tools`, which should be built in the context of the execution platform, instead of the current host platform.

Did you mean to say that `tools` is changing to use the execution platform, or was that supposed to say `exec_tools` and describe the addition of a new attribute? Or was it describing a hypothetical end-state after a long migration process?

**Comment by katre** [comment]
@brandjon This is describing the eventual goal after the migration, which will take quite a long time.

**Comment by gregestren** [comment]
FYI  the review thread link doesn't work for me.

**Comment by katre** [comment]
I removed too many characters, the review thread is https://groups.google.com/forum/#!msg/bazel-dev/5osWxhoF0Fk/1yw4MXrEBQAJ

**Pull request merged**
